version: "3.9"
services:
  tiles:
    container_name: tiles
    image: overv/openstreetmap-tile-server
    volumes:
    - openstreetmap-data:/var/lib/postgresql/12/main
    command: "run"
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim
    volumes:
    - ./postgresdata:/var/lib/postgresql/12/main
    command: "bash /app/start.sh"
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
      - 443:443
    links:
      - tiles
      - nominatim
volumes:
  openstreetmap-data:
    external: true
